development:
  cloud_name: <%= Rails.application.credentials.dig(:production, :cloud_name) %>
  api_key: <%= Rails.application.credentials.dig(:production, :api_key) %>
  api_secret: <%= Rails.application.credentials.dig(:production, :api_secret) %>
production:
  cloud_name: <%= Rails.application.credentials.dig(:production, :cloud_name) %>
  api_key: <%= Rails.application.credentials.dig(:production, :api_key) %>
  api_secret: <%= Rails.application.credentials.dig(:production, :api_secret) %>